// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLn2KS4vgIeCKNPw1XiZv2Aqb5lNDEsrY',
    appId: '1:140736985904:web:63c6414ab5b77ffedb26f5',
    messagingSenderId: '140736985904',
    projectId: 'flutter-midterm-e1196',
    authDomain: 'flutter-midterm-e1196.firebaseapp.com',
    storageBucket: 'flutter-midterm-e1196.firebasestorage.app',
    measurementId: 'G-X5R6YELFZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUy9U67eKB6YMxEBgqpimevXo_SudTzTw',
    appId: '1:140736985904:android:db799eba8601e930db26f5',
    messagingSenderId: '140736985904',
    projectId: 'flutter-midterm-e1196',
    storageBucket: 'flutter-midterm-e1196.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0pcD7k1cLCYiJHsPOtaZr_MVeD_Dod5I',
    appId: '1:140736985904:ios:314e1439cb4a0deedb26f5',
    messagingSenderId: '140736985904',
    projectId: 'flutter-midterm-e1196',
    storageBucket: 'flutter-midterm-e1196.firebasestorage.app',
    iosBundleId: 'com.example.dnt22itb143',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0pcD7k1cLCYiJHsPOtaZr_MVeD_Dod5I',
    appId: '1:140736985904:ios:314e1439cb4a0deedb26f5',
    messagingSenderId: '140736985904',
    projectId: 'flutter-midterm-e1196',
    storageBucket: 'flutter-midterm-e1196.firebasestorage.app',
    iosBundleId: 'com.example.dnt22itb143',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLn2KS4vgIeCKNPw1XiZv2Aqb5lNDEsrY',
    appId: '1:140736985904:web:a023a68d563b138adb26f5',
    messagingSenderId: '140736985904',
    projectId: 'flutter-midterm-e1196',
    authDomain: 'flutter-midterm-e1196.firebaseapp.com',
    storageBucket: 'flutter-midterm-e1196.firebasestorage.app',
    measurementId: 'G-6PL3XXEF2J',
  );
}
